In [15]:
import pandas as pd
recalls = pd.read_csv('recalls_raw.csv')
recalls_cleaned = recalls[recalls.unique == 'Unique']

In [16]:
recalls_cleaned_twice = recalls_cleaned[recalls_cleaned.SEVERITY_SCORE != 0]

In [17]:
recalls_cleaned_twice

,RECORD_ID,MAKETXT,MODELTXT,YEARTXT,SEVERITY_SCORE,unique
0,1,FORD,FOCUS,2001,8,Unique
1,2,FORD,FOCUS,2000,8,Unique
3,4,HOLIDAY RAMBLER,ADMIRAL SE,2003,5,Unique
4,5,HOLIDAY RAMBLER,ADMIRAL SE,2002,5,Unique
5,6,HOLIDAY RAMBLER,ADMIRAL,1999,5,Unique
...,...,...,...,...,...,...
107940,145623,AIRSTREAM,ATLAS,2020,8,Unique
107942,145625,AIRSTREAM,ATLAS,2019,8,Unique
107944,145627,BMW,X4,2020,10,Unique
107945,145628,BMW,X3,2020,10,Unique
107946,145629,VOLVO,VNL,2015,4,Unique

In [18]:
cars_all = pd.read_csv("us_car_models.csv")
cars_all.make

0            Acura
1            Acura
2            Acura
3            Acura
4       Alfa Romeo
           ...
9416        Toyota
9417        Toyota
9418        Toyota
9419         Volvo
9420         Volvo
Name: make, Length: 9421, dtype: object

In [19]:
# makes = ['Acura', 'Alfa Romeo', 'Aston Martin', 'Audi', 'Bentley', 'BMW', 'Buick', 'Cadillac', 'Chevrolet', 'Chrysler', 'Dodge', 'Ferrari', 'FIAT', 'Fisker', 'Ford', 'Genesis', 'GMC', 'Honda', 'HUMMER', 'Hyundai', 'INFINITI', 'Isuzu', 'Jaguar', 'Jeep', 'Kia', 'Lamborghini', 'Land Rover', 'Lexus', 'Lincoln', 'Lotus', 'Maserati', 'Maybach', 'Mazda', 'McLaren', 'Mercedes-Benz', 'Mercury', 'MINI', 'Mitsubishi', 'Nissan', 'Oldsmobile', 'Plymouth', 'Pontiac', 'Porsche', 'Ram', 'Rolls-Royce', 'Saab', 'Saturn', 'Scion', 'smart', 'Subaru', 'Suzuki', 'Toyota', 'Volkswagen', 'Volvo']
makes = list(set(cars_all.make))
makes_upper =[]
for make in makes:
    makes_upper.append(make.upper())
makes_upper[:7]

['TESLA', 'FIAT', 'HUMMER', 'FERRARI', 'ISUZU', 'LAMBORGHINI', 'SUZUKI']

In [20]:
makes = makes_upper

In [21]:
recalls_final = recalls_cleaned_twice.copy()

In [104]:
recalls_final = pd.DataFrame([],columns = ['RECORD_ID', 'MAKETXT', 'MODELTXT','YEARTXT','SEVERITY_SCORE','unique'])
for row in range(len(recalls_cleaned_twice)):
# for row in range(10):
#     print(row)
    if recalls_cleaned_twice.iloc[row].MAKETXT in makes:
#         print("preset")
        recalls_final = recalls_final.append(recalls_cleaned_twice.iloc[row],ignore_index=True)

In [105]:
recalls_final

      RECORD_ID       MAKETXT        MODELTXT YEARTXT SEVERITY_SCORE  unique
0             1          FORD           FOCUS    2001              8  Unique
1             2          FORD           FOCUS    2000              8  Unique
2            44  FREIGHTLINER           FS-65    1996              9  Unique
3            45  FREIGHTLINER           FS-65    1998              9  Unique
4            46  FREIGHTLINER           FS-65    1997              9  Unique
...         ...           ...             ...     ...            ...     ...
35816    145584     CHEVROLET  SILVERADO 1500    2014              5  Unique
35817    145592          FORD          RANGER    2019              8  Unique
35818    145627           BMW              X4    2020             10  Unique
35819    145628           BMW              X3    2020             10  Unique
35820    145629         VOLVO             VNL    2015              4  Unique

[35821 rows x 6 columns]

In [106]:
recalls_final.to_csv('recalls_cleaned.csv')